name: Deploy Website

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
        
        - name: Build
          run: |
            cd ./frontend/vue-project/
            npm run build

        - name: Deploy
          run: |
            aws s3 sync ./frontend/vue-project/dist/ s3://boilerplate.alexrodriguez.link

 
  